### ISSUE TITLE
Plugin requires Rspec gem

### ISSUE THREAD

**Issue by csmosx** [napcs/lazy_developer#2]
The rcov.rake file requires 'spec/rake/spectask'.
This causes all rails rake tasks to abort if the Rspec gem is not in the environment.

Since this is a multi-use sort of plugin, I wouldn't think it's target audience is limited to those using Rspec for their project. I've been wrong before.

**Comment by napcs** [comment]
no you're absolutely right. Edge is broken and we had fixed this but not committed. Things are crazy so I'll just accept your patch.

**Comment by napcs** [comment]
Applied.

**Comment by csmosx** [comment]
Thanks. This reminds me that I should fix my git config (says simplicoder still) haha.
